### ISSUE TITLE
how to set User-Agent ?

### ISSUE THREAD

**Issue by oahzuw** [seleniumQuery/seleniumQuery#145]
System.setProperty("phantomjs.binary.path", "D:/Vbox/phantomjs.exe");
$.driver().usePhantomJS();
$.url("m.fackbook.com");
......
but I do not know how to set user-agent like this :
User-Agent:Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36

can you help me ?

**Comment by acdcjunior** [comment]
Hey, there.

You don't need to call `System.setProperty()` like that. seleniumQuery can do it for you using:

```java
$.driver().usePhantomJS().withPathToPhantomJS("path-to-your-phantomjs-executable");
```

Now, your question is not seleniumQuery specific, it is rather a PhantomJS one, but I do happen to know the answer. To change the user agent of PhantomJS you can do it like this:

```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_PAGE_SETTINGS_PREFIX+"userAgent", "JustAnotherAgent WebKit");

$.driver().usePhantomJS().withPathToPhantomJS("D:/Vbox/phantomjs.exe").withCapabilities(capabilities);
$.url("m.fackbook.com");
```
And your user-agent string changed. Note that it **must** contain the word `WebKit` in it, otherwise the PhantomJS executable does not work and gives crazy error messages.

**Comment by oahzuw** [comment]
Solve the problem, thank you very much :+1:
