### ISSUE TITLE
Compatibility with jBrowserDriver?

### ISSUE THREAD

**Issue by dhruvbhatia** [seleniumQuery/seleniumQuery#172]
Firstly, great library!

Is it possible to use seleniumQuery with [jBrowserDriver](https://github.com/MachinePublishers/jBrowserDriver)?

As [per this issue](https://github.com/MachinePublishers/jBrowserDriver/issues/151#issuecomment-231571326), I can pass an instance of jBrowserDriver to `$.driver().use(driver);`(since jBD extends `WebDriver`) but all subsequent calls to `$` result in a hang.

**Comment by hollingsworthd** [comment]
This is fixed now. jBrowserDriver was expecting By to be Serializable but there was an easy fix for that.

**Comment by dhruvbhatia** [comment]
Excellent, thanks for the quick fix. 👍

**Comment by acdcjunior** [comment]
This is great news.
As soon as the fix is released, I will create a job to run the e2e tests suite of seleniumQuery using jBrowserDriver.

I would have it included by default in seleniumQuery (such as HtmlUnit and PhantomJS are now), but this is not possible at the moment because we still use Java 7 (the same as Selenium itself) and jBrowserDriver uses Java 8. The next major release of Selenium will probably require Java 8, so it shouldn't take long.
