### ISSUE TITLE
How to wait for ajax?

### ISSUE THREAD

**Issue by zhengzhiqiang** [seleniumQuery/seleniumQuery#92]
Hello,i want to know how to wait for ajax complete,because i always find "No such element Exception".What can I do?Thanks.

**Comment by acdcjunior** [comment]
When dealing with Selenium-related code (I mean, this is not specific to seleniumQuery), you have to wait for something from the user perspective.

In other words, Selenium can't "wait for ajax", because the, for instance, socket ajax opens, is on the background, the user does not have access to that - so Selenium doesn't also.

The fix is having your code wait for the element the user should see when the ajax completes.

Example:
Say clicking a button dispatches an ajax request and at the end of that request a modal pops up.
To get this done, find out a selector that matches that modal, such as its id, and wait for it.
In code, if the modal's `id` attribute is, say, `warningModal`, you would wait like:

    $("#warningModal").waitUntil().is(":visible");

Does that help? Or were you already doing that?

**Comment by zhengzhiqiang** [comment]
I find solution:
 protected void waitForAjax() {
        StepContextUtil.getDriverWait().until(new ExpectedCondition<Boolean>() {
            @Override
            public Boolean apply(WebDriver driver) {
                JavascriptExecutor jsExecutor = (JavascriptExecutor) StepContextUtil.getMainDriver();
                return (Boolean) jsExecutor.executeScript("return window.jQuery && window.jQuery.active == 0");
            }
        });
    }

if element will visible after ajax,invoke waitForAjax above,that will effective.

**Comment by acdcjunior** [comment]
Awesome, then!
